services:
  php:
    build: .
    tty: true
    entrypoint: /bin/bash
    ports:
      - "9000:9000"
    volumes:
      - ./:/app
      - ~/.gitconfig:/home/root/.gitconfig
      - ~/.ssh:/home/root/.ssh
    working_dir: /app
