name: Build HydePHP Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, xml, ctype, json, tokenizer
          coverage: none

      - name: Install Composer dependencies
        run: |
          cd src && composer install

      - name: Build HydePHP project
        run: |
          cd src && php hyde build

      - name: deploy docs
        uses: appleboy/gh-pages-action@v0.0.2
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          remote_url: https://github.com/Ethicoders/ethicode.git
          target_branch: gh-pages
          target_directory: docs